#!/bin/sh

HTTP_PORT=$(grep ^http_port ../etc/pcapdb.cfg | awk -F= '{{ print $2 }}' | tr -d '[[:space:]]')

if [ -z "${HTTP_PORT}" ]; then
    URI=$(hostname)
else
    URI=$(hostname):${HTTP_PORT}
fi

../bin/python manage.py runserver ${URI}
